name: Boomflow Badge Sync
on:
  schedule:
    - cron: "0 0 * * *" # Diario a medianoche
  workflow_dispatch: # Permite ejecución manual

jobs:
  sync-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jeremy-sud/boomflow/github-action@main
        with:
          bloomflow_token: ${{ secrets.BOOMFLOW_TOKEN }}
          github_username: ${{ github.actor }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🌸 Update Bloomflow badges"
